title: Yamila Garcia
remote_theme: academicpages/academicpages
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: "Yamila Garcia"
  avatar: "/pic2.jpg"
  bio: "Master's Student in CSE | Remote Sensing | Machine Learning"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yng89"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/yamilangarcia/"
